TeamsManageApplication/Models/ErrorViewModel.cs
namespace TeamsManageApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TeamsManageApplication/Components/UpcomingHomeGamesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TeamsManageApplication.DataAccess;

namespace TeamsManageApplication.Components
{
    public class UpcomingHomeGamesViewComponent : ViewComponent
    {
        private readonly TeamsDbContext _teamsDbContext;

        public UpcomingHomeGamesViewComponent(TeamsDbContext teamsDbContext)
        {
            _teamsDbContext = teamsDbContext;
        }

        public IViewComponentResult Invoke(int maxToDisplay, int numberOfWeeks)
        {
            DateTime now = DateTime.Now;
            DateTime futureDate = now.AddDays(7 * numberOfWeeks);

            var games = _teamsDbContext.Games
                    .Include(g => g.Team)
                    .Where(g => g.Date > now && g.Date <= futureDate)
                    .OrderByDescending(g => g.Date)
                    .Take(maxToDisplay)
                    .ToList();

            GamesViewModel upcomingGamesViewModel = new GamesViewModel()
            {
                Games = games,
                NumberOfWeeks = numberOfWeeks
            };

            return View(upcomingGamesViewModel);

        }
    }
}

TeamsManageApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TeamsManageApplication.Models;

namespace TeamsManageApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeamsManageApplication/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Teams.Entities;
using TeamsManageApplication.Components;
using TeamsManageApplication.DataAccess;

namespace TeamsManageApplication.Controllers
{
    public class TeamController : Controller
    {
        public TeamController(TeamsDbContext teamsDbContext)
        {
            _teamsDbContext = teamsDbContext;
        }

        [HttpGet("/teams")]
        public IActionResult GetAllTeams()
        {
            var teams = _teamsDbContext.Teams
                    .Include(t => t.Players)
                    .Include(t => t.Games)
                    .OrderByDescending(t => t.DateCreated)
                    .ToList();

            return View("Items", teams);
        }

        [HttpGet("/teams/{id}")]
        public IActionResult GetTeamById(int id)
        {
            var team = _teamsDbContext.Teams
        .Include(t => t.Players)
        .Include(t => t.Games)
        .FirstOrDefault(t => t.TeamId == id);

            var viewModel = new TeamDetailsViewModel
            {
                Team = team,
                NewPlayer = new Player(),
                NewGame = new Game()
            };

            return View("Details", viewModel);
        }

        [HttpGet("/teams/add-request")]
        public IActionResult GetAddTeamRequest()
        {
            return View("AddTeam", new Team());
        }

        [HttpPost("/teams")]
        public IActionResult AddNewTeam(Team team)
        {
            if (ModelState.IsValid)
            {
                _teamsDbContext.Teams.Add(team);
                _teamsDbContext.SaveChanges();

                TempData["LastActionMessage"] = $"The team \"{team.Name}\" was added.";

                return RedirectToAction("GetAllTeams", "Team");
            }
            else
            {
                return View("AddTeam", team);
            }
        }

        [HttpGet("/teams/{id}/edit-request")]
        public IActionResult GetEditRequestById(int id)
        {
            var team = _teamsDbContext.Teams.Find(id);
            return View("EditTeam", team);
        }

        [HttpPost("/teams/edit-requests")]
        public IActionResult ProcessEditRequest(Team team)
        {
            if (ModelState.IsValid)
            {
                _teamsDbContext.Teams.Update(team);
                _teamsDbContext.SaveChanges();

                TempData["LastActionMessage"] = $"The team \"{team.Name}\" was updated.";

                return RedirectToAction("GetAllTeams", "Team");
            }
            else
            {
                return View("EditTeam", team);
            }
        }

        [HttpGet("/teams/{id}/delete-request")]
        public IActionResult GetDeleteRequestById(int id)
        {
            var team = _teamsDbContext.Teams.Find(id);
            return View("DeleteConfirmation", team);
        }

        [HttpPost("/teams/{id}/delete-requests")]
        public IActionResult ProcessDeleteRequestById(int id)
        {
            var team = _teamsDbContext.Teams.Find(id);

            _teamsDbContext.Teams.Remove(team);
            _teamsDbContext.SaveChanges();

            TempData["LastActionMessage"] = $"The team \"{team.Name}\" was deleted.";

            return RedirectToAction("GetAllTeams", "Team");
        }

        private TeamsDbContext _teamsDbContext;

        [HttpPost("/teams/{id}/players")]
        public IActionResult AddPlayer(int id, Player player)
        {
            if (ModelState.IsValid)
            {
                player.TeamId = id;
                _teamsDbContext.Players.Add(player);
                _teamsDbContext.SaveChanges();
                return RedirectToAction("GetTeamById", new { id = id });
            }

            // If validation fails, reload the team details with the current data
            var team = _teamsDbContext.Teams
                .Include(t => t.Players)
                .Include(t => t.Games)
                .FirstOrDefault(t => t.TeamId == id);

            var viewModel = new TeamDetailsViewModel
            {
                Team = team,
                NewPlayer = player,
                NewGame = new Game()
            };

            return View("Details", viewModel);
        }
    }
}

TeamsManageApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Final Exam for Chiayin Yang (Student #: 8954164)";
}

<p>
    <a asp-controller="Team" asp-action="GetAllTeams">View all teams</a>
    <span class="mx-1">|</span>
    <a asp-controller="Team" asp-action="GetAddTeamRequest">Add a new team</a>
</p>
<div class="row">
    <div class="col-sm-6">
        @await Component.InvokeAsync("RecentPastGames", new { maxToDisplay = 3, numberOfWeeks = 10 })
    </div>
    <div class="col-sm-6">
        @await Component.InvokeAsync("UpcomingHomeGames", new { maxToDisplay = 3, numberOfWeeks = 10 })
    </div>
</div>

TeamsManageApplication/Views/Shared/Components/RecentPastGames/Default.cshtml
@model TeamsManageApplication.Components.GamesViewModel

<h3>Recent Games</h3>
<h6>Games in the last @Model.NumberOfWeeks weeks</h6>
<ul>
    @foreach (Teams.Entities.Game g in Model.Games)
    {
        <li>Played @g.OpposingTeamName on @g.Date?.ToString("d")</li>
    }
</ul>

TeamsManageApplication/Views/Shared/Components/UpcomingHomeGames/Default.cshtml
@model TeamsManageApplication.Components.GamesViewModel

<h3>Upcoming Home Games</h3>
<h6>Home games in the next @Model.NumberOfWeeks weeks</h6>
<ul>
    @foreach (Teams.Entities.Game g in Model.Games)
    {
        <li>Playing @g.OpposingTeamName on @g.Date?.ToString("d")</li>
    }
</ul>

TeamsManageApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamsManageApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/redmond/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TeamsManageApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeamsManageApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <last-action-message></last-action-message>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TeamsManageApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TeamsManageApplication/Views/Shared/_TeamForm.cshtml
@model Teams.Entities.Team

<div class="text-danger" asp-validation-summary="All"></div>

<div class="form-group">
    <label asp-for="Name">Name</label>
    <input type="text" asp-for="Name" class="form-control" />
</div>

<div class="form-group">
    <label asp-for="DateCreated">Date created</label>
    <input type="datetime" asp-for="DateCreated" class="form-control" value="@Model.DateCreated?.ToString("d")" />
</div> 

TeamsManageApplication/Views/Team/AddTeam.cshtml
@model Teams.Entities.Team

@{
    ViewData["Title"] = "Add Team";
}

<form asp-controller="Team" asp-action="AddNewTeam" method="post" enctype="application/x-www-form-urlencoded">
    @Html.Partial("_TeamForm", Model)

    <button type="submit" class="btn btn-primary">Add</button>
    <a asp-controller="Team" asp-action="GetAllTeams" class="btn btn-primary">Cancel</a>
</form>

TeamsManageApplication/Views/Team/DeleteConfirmation.cshtml
@model Teams.Entities.Team

@{
    ViewData["Title"] = "Delete Team";
}

<h6>Confirm Deletion</h6>
<h3>@Model.Name (Created: @Model.DateCreated?.ToString("d"))</h3>

<form asp-controller="Team" asp-action="ProcessDeleteRequestById" asp-route-id="@Model.TeamId" method="post" enctype="application/x-www-form-urlencoded">
    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Team" asp-action="GetAllTeams" class="btn btn-primary">Cancel</a>
</form>

TeamsManageApplication/Views/Team/Details.cshtml
@model TeamsManageApplication.Components.TeamDetailsViewModel
@{
    ViewData["Title"] = "Manage your team";
}
@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

<div class="mb-3">
    <div class="text-info">@TempData["LastActionMessage"]</div>

    <a asp-controller="Team" asp-action="GetAllTeams">All teams</a>
    <span class="mx-1">|</span>
    <a asp-controller="Team" asp-action="GetAddTeamRequest">Add new team</a>
    <span class="mx-1">|</span>
    <a href="#">Edit this team</a>
</div>

<div>
    <p class="h6">Team summary:</p>
    <p>The team "@Model.Team.Name" was created on @Model.Team.DateCreated?.ToString("MM/dd/yyyy")</p>
</div>
<div class="row g-3 align-items-center">
    <div># of home games: @Model.HomeGameCount  &nbsp;&nbsp;&nbsp; # of away games: @Model.AwayGameCount</div>
</div>

<div class="text-danger" asp-validation-summary="All"></div>

<hr class="border border-primary border-1 opacity-75" />

<div class="row">
    <div class="col-sm-9">
        <p class="h6">Players on this team:</p>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>League registration #</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var player in Model.Team.Players)
                {
                    <tr>
                        <td>@player.LastName, @player.FirstName</td>
                        <td>@player.Number</td>
                        <td>@player.LeagueRegistrationNumber</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-sm-3">
        <form asp-controller="Team" asp-action="AddPlayer" asp-route-id="@Model.Team.TeamId" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="NewPlayer.FirstName">First Name</label>
                <input asp-for="NewPlayer.FirstName" class="form-control" />
            </div>

            <div class="mb-3">
                <label asp-for="NewPlayer.LastName">Last Name</label>
                <input asp-for="NewPlayer.LastName" class="form-control" />
            </div>

            <div class="mb-3">
                <label asp-for="NewPlayer.Number">Number</label>
                <input asp-for="NewPlayer.Number" class="form-control" />
            </div>


            <div class="mb-3">
                <label asp-for="NewPlayer.LeagueRegistrationNumber">League registration #</label>
                <input asp-for="NewPlayer.LeagueRegistrationNumber" class="form-control" />
            </div>

            <button type="submit" class="btn btn-primary">Add Player</button>
        </form>
    </div>

</div>

<hr class="border border-primary border-1 opacity-75" />

<div class="row">
    <div class="col-sm-9">
        <p class="h6">Games for this team:</p>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Opposing Team</th>
                    <th>Date</th>
                    <th>Home/Away</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var game in Model.Team.Games)
                {
                    <tr>
                        <td>@game.OpposingTeamName</td>
                        <td>@game.Date?.ToString("MM/dd/yyyy")</td>
                        <td>@game.GameType</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-sm-3">
        <form asp-controller="Team" asp-action="AddGame" asp-route-teamId="@Model.Team.TeamId" method="post">
            <div class="mb-3">
                <label asp-for="NewGame.OpposingTeamName" class="form-label">Opposing Team</label>
                <input asp-for="NewGame.OpposingTeamName" class="form-control" />
                <span asp-validation-for="NewGame.OpposingTeamName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="NewGame.Date" class="form-label">Date</label>
                <input asp-for="NewGame.Date" class="form-control datepicker" />
                <span asp-validation-for="NewGame.Date" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Add new game</button>
        </form>

    </div>
</div>

<hr class="border border-primary border-1 opacity-75" />

<div>
    <p>
        Ideally this app would allow users to update games with Win/Loss/Tied results but in the
        interest of avoiding too much complexity on this exam we will ignore that for now &#128516;
    </p>
</div>

TeamsManageApplication/Views/Team/EditTeam.cshtml
@model Teams.Entities.Team

@{
    ViewData["Title"] = "Edit Team";
}

<form asp-controller="Team" asp-action="ProcessEditRequest" method="post" enctype="application/x-www-form-urlencoded">
    @Html.Partial("_TeamForm", Model)

    <input type="hidden" asp-for="TeamId" />

    <button type="submit" class="btn btn-primary">Edit</button>
    <a asp-controller="Team" asp-action="GetAllTeams" class="btn btn-primary">Cancel</a>
</form>

TeamsManageApplication/Views/Team/Items.cshtml
@model List<Teams.Entities.Team>

@{
    ViewData["Title"] = "All teams";
}

<a asp-controller="Team" asp-action="GetAddTeamRequest">Add new team</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date created</th>
            <th>Number of players</th>
            <th>Number of games</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var team in Model)
        {
            <tr>
                <td>@team.Name</td>
                <td>@team.DateCreated</td>
                <td>@team.Players?.Count</td>
                <td>@team.Games?.Count</td>
                <td>
                    <a asp-controller="Team" asp-action="GetTeamById" asp-route-id="@team.TeamId">Manage</a>
                    <span class="mx-1">|</span>
                    <a asp-controller="Team" asp-action="GetEditRequestById" asp-route-id="@team.TeamId">Edit</a>
                    <span class="mx-1">|</span>
                    <a asp-controller="Team" asp-action="GetDeleteRequestById" asp-route-id="@team.TeamId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>